export const EXAMPLE_MARKDOWN = `# Implementation Plan

# External API v2 - Implementation Plan

*Sibling docs: see **Executive Brief** for the leadership-facing pitch, and **Operator brainstorm - full social-listening menu** for the long list of operators we may pick up later.*

---

## How to use this doc (the iteration loop)

This doc has two top-level sections that each play a different role:

1. **Agent-generated plan** - the working technical plan. Regenerated by the AI agent on every re-prompt. Do **not** edit this section by hand; your edits will be overwritten on the next regeneration.
2. **Human steering notes** - free-form area where the team writes ideas, constraints, corrections, scoping changes, sequencing preferences. The agent reads this section on every re-prompt and folds your input into the regenerated plan above.

The loop is:

* A teammate adds notes under **Human steering notes** (e.g. "prioritise top_creators ahead of detect_peaks", "we don't actually need page-based pagination, drop it", "add an operator for podcast-host stance").
* They re-prompt the agent in Cursor with: "Update the Implementation Plan in the Linear project; read the Human steering notes and incorporate them."
* The agent fetches this doc, replaces the content between the \`AGENT_PLAN_BEGIN\` / \`AGENT_PLAN_END\` HTML-comment markers, and leaves the human notes untouched.
* We repeat until the plan is ready to break into Linear issues.

The markers are real (not decoration) - they exist so regeneration is mechanical. Please leave them in place.

---

## Agent-generated plan

*Last regenerated: 2026-05-12 (Claude, model: claude-opus-4-7-thinking-xhigh). Source of truth: the chat in Cursor that produced this version.*

<!-- AGENT_PLAN_BEGIN -->

### Goals

* Add a catalog of analytical **operators** that all share a common shape (overrides, response envelope) and each has its own REST endpoint and MCP tool.
* Operators come in two flavours:
  * **Live**: run directly on the Elasticsearch index with an ad-hoc query block (keywords, sources, languages, dates). No monitor needed.
  * **Monitor-bound**: run against a saved monitor and use the per-monitor enrichments we compute asynchronously (sentiment, topic analysis, LLM relevance / noise filter). These cannot be served from the live index because the enrichments do not exist for arbitrary keywords.
* Reuse the existing primitives end-to-end: no rename of \`monitor\` at the API surface, no rename of \`Search\`/\`Query\`/\`Mention\` in the model layer.
* Provide a clear deprecation path for the existing \`/v1/monitor/\` endpoints that are subsumed by v2.

### Non-goals

* No primitive rename. "Monitor" stays as the public name (and \`Search\` stays internally).
* No change to OAuth scopes/auth. v2 reuses \`monitor:read\` / \`monitor:write\` for monitor-bound calls and \`search:read\` for live calls.
* No change to ingestion pipelines (Netfeedr/Twingly/AllEars).
* **No re-indexing of the live ES index** for v2.0. See "Open question: live mention counts" below.

### Concepts

\`\`\`mermaid
flowchart LR
    Live["Live query (ad-hoc)"] -->|"keywords + sources + dates"| LiveOps
    Monitor["Monitor (saved search w/ enrichments)"] -->|"uuid"| AllOps

    subgraph LiveOps["Live-capable operators"]
        EC[episode_count]
        TS[time_series]
        GR[growth_rate]
        DP[detect_peaks]
        TSrc[top_sources]
        TCr[top_creators]
        TTrm[top_terms]
        GM[get_mentions]
    end

    subgraph EnrichedOps["Monitor-only operators"]
        MC[mention_count]
        SD[sentiment_distribution]
        TA["topic_analysis (future)"]
        REL["relevance_filter (future)"]
    end

    LiveOps --> RestLive["REST: /v2/search/{operator}/"]
    LiveOps --> RestMon["REST: /v2/monitor/{uuid}/{operator}/"]
    EnrichedOps --> RestMon
    LiveOps --> Mcp["MCP: tool({query: ...})"]
    EnrichedOps --> Mcp2["MCP: tool({monitor_id: ...})"]

    AllOps -.-> RestMon
\`\`\`

A **monitor** is the existing \`customers.models.Search\` (with \`search_type=BRAND\`), exposed by today's \`MonitorSerializer\`. A monitor produces a continuously enriched stream: every mention gets sentiment, topic labels, and an optional LLM relevance score (the noise filter). These enrichments only exist for monitors because they are too expensive to run against the live firehose.

A **live query** is the same query block we already accept at \`external_api/search_api/serializers/search_api_serializer.py\` (\`search_term\`, \`near_keywords\`, \`not_near_keywords\`, \`sources\`, \`languages\`, \`start_date\`, \`end_date\`). It is evaluated with an ephemeral \`Search\`/\`Query\` pair, exactly as \`SearchApiMentionsList\` does today via \`paginated_search\` in \`customers/search.py\`. We are generalising that pattern: instead of one ad-hoc endpoint that returns mentions, every live-capable operator gets one.

An **operator** is a read-only computation. Every operator accepts the shared \`Overrides\` block on top of its own params; live-capable operators additionally accept the live query block.

### Live vs monitor: what counts as a "mention"

This distinction drives the whole catalog, so it is worth being precise about.

* A **document** in our Elasticsearch index is one indexed content item: a podcast episode, a YouTube video, a TV broadcast, an article, a social post. Internally we call this an \`episode_id\` regardless of source.
* A **mention** is a *chunk inside* a document where our search query matched. The same document can produce many mentions (multiple matches in a long transcript).
* ES gives us a cheap, exact \`hits.total\` for **document** counts on any query. That is what powers \`episode_count\`.
* ES does not give us a cheap, exact aggregate for **mention** counts. Today we materialise mentions only after the fact, by walking the highlight markers (\`<b>...</b>\`) returned for each fetched document - see \`customers/backends/elasticsearch.py::build_highlight_config\` (uses \`number_of_fragments: 0\` to return the whole highlighted field) and the per-hit highlight walking in \`customers/search.py\`. This works for paginated reads but it costs O(documents read), not O(1) - so we cannot offer it as a sub-second aggregate over millions of matches.
* For **monitors**, we already pay this cost asynchronously: the indexing pipeline writes one \`Mention\` row per match into the database, with sentiment, topic, and LLM-relevance enrichments attached. Counting / grouping mentions is then a cheap SQL aggregate.

That asymmetry is why:

* \`episode_count\` is the live primitive; \`mention_count\` is monitor-only.
* \`time_series\`, \`growth_rate\`, \`detect_peaks\`, \`top_sources\`, \`top_creators\`, \`top_terms\` are all live-capable, but in live mode the underlying unit is documents (default \`metric=episodes\`), not mentions.
* A user who needs true mention counts (or any of the enriched fields) is the user who needs a monitor. The 400 we return on monitor-only operators says exactly this.

See "Open question: live mention counts" below for the architectural choices we have if we ever decide to deliver live mention counts cheaply.

### Surface area

#### URLs

\`\`\`
# Monitor CRUD (unchanged)
/v1/monitor/                                    GET, POST  (kept; deprecated)
/v1/monitor/{uuid}/                             GET, PATCH, DELETE  (kept; deprecated)
/v1/monitor/{uuid}/mentions/                    GET  (kept; deprecated alias of v2)
/v1/monitor/{uuid}/metrics/                     GET  (kept; deprecated)

# Live ad-hoc search (existing; kept as alias)
/search/v1/                                     GET  (kept; deprecated alias of /v2/search/mentions/)

# Monitor-bound operators (every operator is reachable here)
/v2/monitor/                                    GET, POST  (CRUD, same MonitorSerializer)
/v2/monitor/{uuid}/                             GET, PATCH, DELETE
/v2/monitor/{uuid}/episode-count/               GET
/v2/monitor/{uuid}/mention-count/               GET
/v2/monitor/{uuid}/time-series/                 GET
/v2/monitor/{uuid}/growth-rate/                 GET
/v2/monitor/{uuid}/detect-peaks/                GET
/v2/monitor/{uuid}/top-sources/                 GET
/v2/monitor/{uuid}/top-creators/                GET
/v2/monitor/{uuid}/top-terms/                   GET
/v2/monitor/{uuid}/sentiment-distribution/      GET
/v2/monitor/{uuid}/mentions/                    GET   (operator: get_mentions, supports cursor mode)

# Live operators (only live-capable ones; ad-hoc query block, no monitor)
/v2/search/episode-count/                       GET
/v2/search/time-series/                         GET
/v2/search/growth-rate/                         GET
/v2/search/detect-peaks/                        GET
/v2/search/top-sources/                         GET
/v2/search/top-creators/                        GET
/v2/search/top-terms/                           GET
/v2/search/mentions/                            GET   (operator: get_mentions; replaces /search/v1/)

# Schema + docs
/v2/schema/                                     GET
/v2/docs/                                       GET
\`\`\`

The new structure puts everything customer-visible under a single \`/v2/\` namespace: \`/v2/monitor/...\` for monitor-bound work and \`/v2/search/...\` for live ad-hoc work. The legacy \`/search/v1/\` endpoint stays mounted as a deprecated alias of \`/v2/search/mentions/\` so existing integrations keep working.

The existing v2 stream endpoints in \`external_api/monitor/v2_urls.py\` (\`/v2/monitor/{uuid}/stream/mentions/\`, \`/stream/sentiment/\`) are subsumed by \`get_mentions\` (cursor mode) and removed.

#### MCP tools

One tool per operator, namespaced \`monitor_<operator>\` for clarity. Each tool accepts either \`monitor_id\` or a \`query\` block; for monitor-only operators, omitting \`monitor_id\` returns a clear error pointing at how to create a monitor.

\`\`\`
monitor_episode_count(query={search_term: "...", ...})           # live (preferred for live)
monitor_episode_count(monitor_id="...")                          # monitor-bound

monitor_mention_count(monitor_id="...")                          # monitor-only
monitor_mention_count(query={search_term: "..."})                # rejected with a 400 pointing at episode_count

monitor_sentiment_distribution(monitor_id="...")                 # monitor-only; query is rejected
\`\`\`

The v1 tools in \`external_api/mcp/tools.py\` (\`list_monitors\`, \`get_monitor\`, \`get_metrics\`, \`search_mentions\`, ...) stay registered as deprecated aliases for the deprecation window with \`[Deprecated]\` prefixed in their docstrings so MCP clients prefer the v2 names.

### The Operator base class

New file \`external_api/operators/base.py\`:

* \`class Operator(APIView)\`
  * \`operator_name: str\` (used in URL and MCP tool name)
  * \`supports_live: bool\` (whether the operator can run on a live query)
  * \`params_serializer_class: Serializer\` (operator-specific params)
  * \`OverridesSerializer\` mixed in (shared)
  * \`compute(monitor, overrides) -> dict\` (always required)
  * \`compute_live(query, overrides) -> dict\` (required iff \`supports_live\`)
  * Boilerplate: \`force_english\`, scope check, error envelope, OpenAPI tags.

Two mixin views call into the operator subclass:

* \`MonitorOperatorView\`: takes \`<uuid>\` from URL, resolves the monitor via \`get_search_or_404\`, calls \`compute\`. Required scope: \`monitor:read\`.
* \`LiveOperatorView\`: validates the live query block via the existing \`SearchApiSerializer\` (lifted into a shared serializer), calls \`compute_live\`. Required scope: \`search:read\`. 404 if \`supports_live=False\`.

Each operator subclass then looks like:

\`\`\`python
class TimeSeriesOperator(Operator):
    operator_name = "time-series"
    supports_live = True
    params_serializer_class = TimeSeriesParamsSerializer

    def compute(self, monitor, overrides):
        return time_series_aggregator(monitor.mentions(), **overrides)

    def compute_live(self, query, overrides):
        ephemeral_search, ephemeral_query = build_ephemeral_search(query, overrides)
        return time_series_aggregator_es(ephemeral_search, ephemeral_query, **overrides)
\`\`\`

A small registry maps operator name to class so URL routing and the MCP tool factory can both walk the same list.

#### Shared \`OverridesSerializer\`

| Field | Type | Default | Notes |
| -- | -- | -- | -- |
| \`start_date\` | date | last 14d (monitor) / last 7d (live) | inclusive |
| \`end_date\` | date | today | inclusive |
| \`as_of_date\` | datetime | null | rewinds the index state; monitor-only |
| \`channel_types\` | csv enum | all | podcast, youtube, tv, radio, online_news, social_media |
| \`languages\` | csv ISO-639 | all (monitor) / monitor-default (live) |  |
| \`sentiment\` | enum | all | monitor-only |
| \`min_reach\` | int | 0 |  |
| \`currency\` | ISO-4217 | USD | only used by reach/PR-value operators |

Filters that depend on enrichments (\`sentiment\`, \`min_relevance\`, \`topic\`) are silently ignored on the live path; passing them with \`query\` returns a 400 with a clear error so callers know they need a monitor.

#### Shared live \`QuerySerializer\`

Lifted from \`external_api/search_api/serializers/search_api_serializer.py\`. For querystring-friendliness on \`/v2/search/{operator}/?...\` we accept the same flat params (\`search_term\`, \`near_keywords\`, etc.). For MCP we accept the same fields nested under \`query\`.

### Operator catalog (v2.0 - first batch)

This is what we ship now. Legend: **L** = live-capable, **M** = monitor-bound only.

#### 1\. \`episode_count\`  (L + M)

The honest live primitive: how many distinct content items (episodes / videos / articles / posts) match the query.

* Inputs: \`group_by?: "channel_type" | "language" | null\`
* Response: \`{ count: 1234 }\` or \`{ groups: [{key, count}, ...], total }\`
* Live: ES \`hits.total\` for the total; ES \`terms\` aggregation for the grouped form.
* Monitor: \`monitor.mentions().values("episode_id").distinct().count()\` (and grouped equivalents).
* Note: across all sources we name this "episodes" for consistency with v1 metrics, even when the underlying unit is a YouTube video, an article, or a TikTok post.

#### 2\. \`mention_count\`  (M only)

Counts the per-mention rows our monitor pipeline materialises, with optional grouping that requires the enriched fields.

* Inputs: \`group_by?: "channel_type" | "language" | "sentiment" | null\`
* Response: same envelope as \`episode_count\`.
* Live form is rejected with \`{"error": "operator_requires_monitor", "detail": "mention_count counts enriched mentions inside documents, which only exist for monitors. Use /v2/search/episode-count/ for live document counts, or create a monitor for true mention counts and sentiment grouping."}\`.

#### 3\. \`time_series\`  (L + M)

* Inputs: \`granularity: "hour"|"day"|"week"|"month"\` (default \`day\`), \`metric\` (see below).
* Live \`metric\`: \`"episodes"\` (default), \`"reach"\`, \`"pr_value"\`.
* Monitor \`metric\`: \`"episodes"\` (default), \`"mentions"\`, \`"reach"\`, \`"pr_value"\`, \`"net_sentiment"\`.
* Response: \`{ granularity, metric, points: [{bucket, value}, ...] }\`
* Live: ES \`date_histogram\`. Monitor: \`Trunc<Granularity>\` aggregation generalising \`external_api/monitor/views/monitor_mentions_metrics_view.py\`.

#### 4\. \`growth_rate\`  (L + M)

* Inputs: \`period: "wow"|"mom"|"qoq"|"yoy"\` (default \`wow\`) OR \`compare_to: {start_date, end_date}\`. Same \`metric\` enum as \`time_series\`.
* Response: \`{ metric, current: {start, end, value}, baseline: {start, end, value}, delta, delta_pct }\`
* Implementation: two \`episode_count\`/\`mention_count\` calls over two windows.

#### 5\. \`detect_peaks\`  (L + M)

* Inputs: \`granularity\` (default \`day\`), \`metric\` (default \`episodes\` live, \`mentions\` monitor), \`z_threshold\` (default \`2.0\`), \`min_count\` (default \`5\`).
* Algorithm: rolling mean + stdev (28-bucket window) on the time_series result, flag \`(value - mean) / stdev >= z_threshold\`.
* Response: \`{ metric, peaks: [{bucket, value, baseline_mean, z_score}, ...] }\`

#### 6\. \`top_sources\`  (L + M)

* Inputs: \`limit\` (default 10, max 100), \`rank_by\`.
* Live \`rank_by\`: \`"episodes"\` (default), \`"reach"\`, \`"pr_value"\`.
* Monitor \`rank_by\`: \`"episodes"\` (default), \`"mentions"\`, \`"reach"\`, \`"pr_value"\`.
* Response: \`{ rank_by, results: [{channel: {id, name, type}, episodes, mentions?, reach, pr_value}, ...] }\`
* Live: ES \`terms\` agg on \`channel_id\` with sub-aggs for reach / pr_value. Monitor: reuses \`reports/widgets/insights_top_channels.py\`.

#### 7\. \`top_creators\`  (L + M)

Twin of \`top_sources\`, ranked at the host / guest / author / creator level.

* Inputs: \`limit\` (default 10, max 100), \`rank_by\` same enum as \`top_sources\`, \`role?: "host"|"guest"|"author"|"creator"|"any"\` (default \`any\`).
* Response: \`{ rank_by, results: [{creator: {id, name, role, channel_id?}, episodes, mentions?, reach, engagement?}, ...] }\`
* Live: ES \`terms\` agg on the creator id field present on each document. Monitor: same plus the \`mentions\` count.

#### 8\. \`top_terms\`  (L + M)

* Inputs: \`limit\` (default 25), \`kind: "term"|"hashtag"|"entity"\` (default \`term\`), \`min_doc_freq\` (default 5).
* Response: \`{ kind, results: [{term, doc_count, score, examples: ["...mention id..."]}, ...] }\`
* Live: ES \`significant_terms\` agg over the matched documents. \`kind=entity\` is monitor-only because it depends on NER enrichment; the live form returns 400 if \`kind=entity\` is requested.
* Useful for seeing which co-mentioned brands, hashtags, or named entities are co-occurring with the query.

#### 9\. \`sentiment_distribution\`  (M only)

* Inputs: none beyond overrides.
* Response: \`{ positive, negative, neutral, total, share: {positive, negative, neutral}, net_sentiment }\`
* Why M-only: depends on per-mention \`sentiment_float\` which is computed asynchronously by our sentiment worker only for mentions tied to a monitor.

#### 10\. \`get_mentions\`  (L + M, with two pagination modes)

The only operator with two pagination modes. Clients pick exactly one; mixing them is a 400.

**Mode A: page-based** (the same as v1, for ad-hoc browsing / UIs)

* Inputs: \`page\`, \`page_size\`, \`sort_by\` (\`-created\` default), plus all shared overrides + (live form) the live query block.
* Response: existing v1 mention card shape with \`next\`, \`previous\`, \`count\`, \`page_count\`.

**Mode B: cursor-based** (replaces today's \`/v2/.../stream/mentions/\` and \`/stream/sentiment/\`)

* Inputs:
  * \`cursor\`: opaque string returned by a previous call. Encodes \`(indexed_at, mention_id)\` for stable tiebreaking.
  * \`since\`: ISO-8601 datetime to start from on the first poll. If both \`cursor\` and \`since\` are absent, defaults to "now" so initial calls do not dump the entire backlog.
  * \`page_size\`: 1-1000, default 100.
  * \`sort_by\` is ignored in this mode (always ascending by index date + id).
* Sort key: \`Mention.created\` (the index date, monotonic on insertion), tiebroken on \`id\`. This is the right key for "pick up where I left off" because \`published_date\` can move retroactively when historical content is ingested.
* Algorithm: decode \`(after_created, after_id)\`, build \`Q(created__gt=after_created) | (Q(created=after_created) & Q(id__gt=after_id))\`, order by \`created, id\`, slice \`[: page_size + 1]\`, set \`has_more\`, encode the last returned row as the new \`next_cursor\`.

##### Field visibility on live vs. monitor

| Field | Live | Monitor |
| -- | -- | -- |
| \`text\`, \`context\`, \`published_date\`, \`url_with_timing\`, \`channel\`, \`episode\` | yes | yes |
| \`sentiment\`, \`sentiment_value\` | no (null) | yes |
| \`topic_names\`, \`tags\` | no | yes |
| \`llm_relevance\` | no | yes (when opted in) |
| \`pr_value\` | yes (computed from reach + CPI) | yes |

Live \`get_mentions\` explicitly nulls the enrichment fields and includes a \`notice: "Enrichments (sentiment, topics, llm_relevance) are only available for mentions tied to a monitor."\` so agents can decide whether to ask the user to create a monitor.

### Open question: live mention counts

The user-facing question is "can we ever offer a true \`mention_count\` live, without requiring a monitor?" There are three honest options:

1. **Stay as-is (recommended for v2.0).** Live = document counts only (\`episode_count\`). Mention counts are a monitor benefit. This is honest, cheap, and easy to communicate.
2. **Re-index the firehose into \~200-word windows.** Each transcript becomes N small ES documents. \`hits.total\` on a windowed query then approximates "mentions": each window with at least one match counts as one. Trade-offs:
   * Index size grows roughly 5-20x (a 30-minute podcast with \~5,000 words becomes \~25 windows).
   * Phrase / NEAR queries that straddle a window boundary will miss matches; mitigations are overlapping windows (more index inflation) or a query-time rewrite that ORs adjacent windows (more query cost).
   * Multiple matches in the same window collapse to a count of 1, so it is a *lower bound* on true mention count, not the truth.
   * Existing aggregations and the highlight-driven mention extractor would have to be rewritten to know about windows.
3. **Per-document** \`term_vectors\` for live counts. Cheap per document, but the API call is per-document, not aggregateable - so it works for top-N previews ("on the top 50 matching documents, here is the average mention density") but not for an aggregate count over millions of matches.

For v2.0 we ship option 1. If real customer demand materialises, we can layer option 3 on top as \`episode_count?include_mention_density=true&sample=50\` (cheap and additive). Option 2 is a much bigger architectural commitment and we should only take it if mention-count-grade live analytics becomes a top-three sales blocker.

### Candidate operators (next-up if v2.0 lands well)

Held back from the first batch on purpose, but high-signal candidates if customers ask for them. Each one is a small, well-shaped extension of the v2.0 catalog.

* \`share_of_voice\`  (L + M) - compare one keyword/monitor against a peer set. Built directly on top of \`episode_count\` / \`mention_count\`.
* \`change_point_detection\`  (L + M) - structural break detection on \`time_series\` (PELT / binary segmentation via the \`ruptures\` library). Complements \`detect_peaks\` for spotting regime changes rather than spikes.
* \`crisis_score\`  (M, LLM optional) - composite of \`detect_peaks\` × negative-sentiment trend × reach × geographic spread × controversy. Ship without LLM narrative first; add \`include_explanation\` flag in a follow-up.
* \`top_hosts\` / \`top_guests\`  (L + M, podcast-specific) - filtered variants of \`top_creators\` on Episode author-role.

For the long brainstorm of every operator a social-listening analyst could conceivably want (volume / momentum / voice / context / sentiment / themes / comparison / crisis / channel-specific), see the sibling **Operator brainstorm - full social-listening menu** document. We will graduate items from there into this plan as customer signal arrives.

### Deprecation of v1

* Add \`Deprecation\` and \`Sunset\` HTTP headers on every \`/v1/monitor/*\` and \`/search/v1/\` response. Sunset date is set to "now + 9 months" via env var \`EXTERNAL_API_V1_SUNSET_DATE\`.
* Add a \`Link: <https://docs.allears.ai/api/v2/migration>; rel="deprecation"\` header.
* Mark v1 schema in \`external_api/schema.py\` with \`deprecated: true\` and a top-of-page banner in the redoc view.
* v1 MCP tools get \`[Deprecated]\` prefix in their docstrings so LLMs prefer v2.
* After sunset: delete the legacy v1 monitor URLs from \`external_api/monitor/urls.py\`; the underlying view classes stay because v2 still mounts them for the CRUD routes.

### Spec with worked examples

All examples assume \`Authorization: Bearer <token>\`.

#### \`episode_count\` - live (the new live primitive)

\`GET /v2/search/episode-count/?search_term=heat%20pump&start_date=2026-03-01&end_date=2026-03-31&group_by=channel_type\`

\`\`\`json
{
  "operator": "episode_count",
  "mode": "live",
  "window": {"start_date": "2026-03-01", "end_date": "2026-03-31"},
  "groups": [
    {"key": "podcast", "count": 412},
    {"key": "youtube", "count": 188}
  ],
  "total": 600
}
\`\`\`

#### \`mention_count\` - monitor-bound

\`GET /v2/monitor/{uuid}/mention-count/?start_date=2026-03-01&end_date=2026-03-31&group_by=sentiment\`

\`\`\`json
{
  "operator": "mention_count",
  "mode": "monitor",
  "monitor_id": "4f1c...",
  "groups": [
    {"key": "positive", "count": 320},
    {"key": "neutral",  "count": 220},
    {"key": "negative", "count":  60}
  ],
  "total": 600
}
\`\`\`

#### \`mention_count\` rejecting a live call

\`GET /v2/search/mention-count/?search_term=heat%20pump\`

\`\`\`json
{
  "error": "operator_requires_monitor",
  "detail": "mention_count counts enriched mentions inside documents, which only exist for monitors. Use /v2/search/episode-count/ for live document counts, or create a monitor for true mention counts and sentiment grouping.",
  "alternatives": ["/v2/search/episode-count/", "POST /v2/monitor/"]
}
\`\`\`

#### \`growth_rate\` - monitor-bound

\`GET /v2/monitor/{uuid}/growth-rate/?period=wow&metric=mentions\`

\`\`\`json
{
  "operator": "growth_rate",
  "metric": "mentions",
  "current":  {"start_date": "2026-04-16", "end_date": "2026-04-22", "value": 142},
  "baseline": {"start_date": "2026-04-09", "end_date": "2026-04-15", "value": 121},
  "delta": 21,
  "delta_pct": 17.36
}
\`\`\`

#### \`top_creators\` - live

\`GET /v2/search/top-creators/?search_term=heat%20pump&limit=5&rank_by=reach&role=guest\`

\`\`\`json
{
  "operator": "top_creators",
  "mode": "live",
  "rank_by": "reach",
  "results": [
    {"creator": {"id": "p_5523", "name": "Jane Doe", "role": "guest"}, "episodes": 12, "reach": 1450000},
    {"creator": {"id": "p_8841", "name": "John Smith", "role": "guest"}, "episodes":  9, "reach":  812000}
  ]
}
\`\`\`

#### \`sentiment_distribution\` rejecting a live call

\`GET /v2/search/sentiment-distribution/?search_term=heat%20pump\`

Returns \`404 Not Found\` (operator is monitor-only and not registered under \`/v2/search/\`). The OpenAPI schema reflects this so generated clients never offer it.

#### MCP tool examples

\`\`\`
# Live-capable operator on a live query
monitor_time_series(query={search_term: "heat pump", sources: ["podcast"]},
                    granularity="week", metric="episodes",
                    start_date="2026-01-01", end_date="2026-04-01")

# Same operator against a saved monitor
monitor_time_series(monitor_id="4f1c...", granularity="week", metric="net_sentiment",
                    start_date="2026-01-01", end_date="2026-04-01")

# Monitor-only operator: query rejected
monitor_sentiment_distribution(query={search_term: "heat pump"})  # -> 400 with operator_requires_monitor
\`\`\`

### Testing

* One \`test_<operator>_view.py\` per operator, exercising both live and monitor modes when applicable.
* One parametrized \`test_overrides.py\` that hits every operator with each override and asserts narrowing.
* One \`test_consistency.py\` that, for each live-capable operator with a shared metric (\`episodes\`, \`reach\`, \`pr_value\`), builds a monitor whose query exactly matches the live query block and asserts both modes return the same numbers (modulo enrichment-only fields).
* One \`test_monitor_only_operators.py\` that asserts \`/v2/search/{op}/\` returns the documented 400 / 404 for monitor-only operators.
* \`test_mcp_tools_v2.py\` calls each tool via the in-process \`_call_view\` helper.

### Rollout sequence

**v2.0 (MVP - the work in this plan):**

1. Land the operator base class, registry, and the two URL prefixes (\`/v2/monitor/\` and \`/v2/search/\`) wired to do nothing useful (404s).
2. Ship \`episode_count\` and \`time_series\` in both modes (live + monitor) behind a feature flag, plus monitor-only \`mention_count\`.
3. Add the remaining live-capable v2.0 operators (\`growth_rate\`, \`detect_peaks\`, \`top_sources\`, \`top_creators\`, \`top_terms\`).
4. Add monitor-only \`sentiment_distribution\`; document the live-call contract.
5. Recast \`get_mentions\` with both pagination modes; remove the v2 stream endpoints; mount \`/v2/search/mentions/\` and keep \`/search/v1/\` as a deprecated alias.
6. Generate v2 OpenAPI schema + redoc page + MCP tools (registry-driven, no per-operator boilerplate).

**v2 deprecation:**

7. Turn on Deprecation/Sunset headers on v1 (\`/v1/monitor/*\`, \`/search/v1/\`) and publish the migration guide.
8. After the sunset window: delete the v1 URL routes (views stay for v2 CRUD).

**Candidates (only if customer signal):**

 9. Ship \`share_of_voice\` (cheap, all on the existing primitives).
10. Ship \`change_point_detection\` (one new dependency: \`ruptures\`).
11. Ship \`crisis_score\` without the LLM explanation first; add the LLM narrative behind a separate flag.
12. Ship podcast-specific conveniences \`top_hosts\`, \`top_guests\`.

<!-- AGENT_PLAN_END -->

---

## Human steering notes

*Add ideas / constraints / corrections / sequencing preferences here. Anything in this section is read by the agent on every re-prompt and folded into the regenerated plan above. The agent will not overwrite anything between the markers below, so keep them in place.*

*Examples of useful inputs:*

* *"Drop page-based pagination from get_mentions; cursor-only."*
* *"Push share_of_voice ahead of detect_peaks - sales sees more demand for it."*
* *"We don't want a /search/v2/ namespace; live ops should be at /v2/operators/{name}/ instead."*
* *"Add a 'sound_origin_chain' operator for TikTok."*
* *"Crisis_score has to be billable as a single 50-unit call, not as the sum of its parts."*

<!-- HUMAN_INPUT_BEGIN -->

*(empty - add your notes here. Bullets, prose, or sections all work.)*

* FO: Do we have the type \`entity\` in elastic still? See operator \`top_terms\`.
* FO: Re "**Re-index the firehose into \~200-word windows."**: this is the equivalent of a rough chunking of documents that might work for a RAG implementation. We can embed each window (small doc) and thereby allow for semantic search.
* FO: the proposed \`crisis_score\` is made up of parts that are undefined, e.g., . \`controversy\`. Let's define what we mean by \`crisis_score\` before deciding on its parts.
* AG: For the live search endpoints, the user can now only search for one keyword as far as I understand? Do we not want full search support, like we have in our archive search? Ie. support for multiple keyword clauses, where each clause allows for specifying keywords, near_keywords, near_near_keywords, not_near_keywords, distances etc.?

<!-- HUMAN_INPUT_END -->

---

## Change log

*Auto-maintained by the agent. Each entry: date, who/what produced the change, one-line summary.*

* **2026-05-12 (v2)** - Refactored from chat (Claude). Live ops moved from \`/search/v2/\` to \`/v2/search/\` so the whole public surface lives under \`/v2/\`. Split the count operator into \`episode_count\` (live + monitor, the natural ES primitive) and \`mention_count\` (monitor-only, since mentions are a per-monitor enrichment). Promoted \`top_creators\` and \`top_terms\` into the v2.0 first batch. Removed \`top_sounds\`. Demoted \`share_of_voice\`, \`change_point_detection\`, \`crisis_score\`, \`top_hosts\`/\`top_guests\` to a Candidates section. Moved the full social-listening brainstorm out into the sibling "Operator brainstorm - full social-listening menu" document.
* **2026-05-12** - Initial version pushed from Cursor chat (Claude). v2.0 catalog, v2.1 social-listening expansion, full brainstorm addendum.`
